name: jawara
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # Date & Time Formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Uncomment jika ingin menambahkan assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Uncomment jika ingin menambahkan custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700